# Generated by Django 5.2.6 on 2025-09-14 23:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='clasificacion_procesal',
            field=models.CharField(choices=[('DEMANDANTE', 'Demandante'), ('DEMANDADO', 'Demandado'), ('OTRO', 'Otro')], default='OTRO', max_length=15, verbose_name='Clasificación procesal'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nit',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='El NIT debe contener entre 7 y 15 dígitos.', regex='^\\d{7,15}$')], verbose_name='NIT'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ci',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='El CI debe tener entre 5-8 dígitos, opcionalmente seguido de guion y extensión (ej: 1234567-1A).', regex='^\\d{5,8}(-[A-Z0-9]{1,3})?$')], verbose_name='CI'),
        ),
    ]
