# Generated by Django 5.2.6 on 2025-09-12 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tipo de documento',
                'verbose_name_plural': 'Tipos de documento',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Apoya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tareas', models.CharField(blank=True, max_length=150)),
                ('fecha_ini', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('FINALIZADO', 'Finalizado')], default='ACTIVO', max_length=12)),
                ('auxiliar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.auxiliar')),
            ],
            options={
                'verbose_name': 'Apoyo (Auxiliar en Caso)',
                'verbose_name_plural': 'Apoyos (Auxiliares en Casos)',
            },
        ),
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_caso', models.CharField(max_length=50, unique=True, verbose_name='Nro. Caso')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('EN_PROCESO', 'En proceso'), ('CERRADO', 'Cerrado'), ('ARCHIVADO', 'Archivado')], default='ABIERTO', max_length=12)),
                ('descripcion', models.TextField(blank=True)),
                ('apelaciones', models.TextField(blank=True)),
                ('tipo_de_caso', models.CharField(blank=True, max_length=100)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('auxiliares', models.ManyToManyField(related_name='casos', through='gestdocu.Apoya', to='accounts.auxiliar')),
            ],
            options={
                'verbose_name': 'Caso',
                'verbose_name_plural': 'Casos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddField(
            model_name='apoya',
            name='caso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestdocu.caso'),
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código de expediente')),
                ('fecha_creacion', models.DateField(blank=True, null=True)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('autoridad', models.CharField(blank=True, max_length=150)),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado'), ('ARCHIVADO', 'Archivado')], default='ABIERTO', max_length=10)),
                ('observaciones', models.TextField(blank=True)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedientes', to='gestdocu.caso')),
            ],
            options={
                'verbose_name': 'Expediente',
                'verbose_name_plural': 'Expedientes',
                'ordering': ['caso', 'codigo'],
                'unique_together': {('caso', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Participa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=10)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('abogado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.abogado')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestdocu.caso')),
            ],
            options={
                'verbose_name': 'Participación (Abogado en Caso)',
                'verbose_name_plural': 'Participaciones (Abogados en Casos)',
                'unique_together': {('caso', 'abogado')},
            },
        ),
        migrations.AddField(
            model_name='caso',
            name='abogados',
            field=models.ManyToManyField(related_name='casos', through='gestdocu.Participa', to='accounts.abogado'),
        ),
        migrations.CreateModel(
            name='Tiene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_procesal', models.CharField(blank=True, max_length=100)),
                ('fecha_incorporacion', models.DateField(blank=True, null=True)),
                ('estado_participacion', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=10)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestdocu.caso')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.cliente')),
            ],
            options={
                'verbose_name': 'Vinculación (Cliente en Caso)',
                'verbose_name_plural': 'Vinculaciones (Clientes en Casos)',
                'unique_together': {('caso', 'cliente')},
            },
        ),
        migrations.AddField(
            model_name='caso',
            name='clientes',
            field=models.ManyToManyField(related_name='casos', through='gestdocu.Tiene', to='accounts.cliente'),
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('archivo', models.FileField(upload_to='documentos/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_creados', to=settings.AUTH_USER_MODEL)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='gestdocu.expediente')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='gestdocu.tipodocumento')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='apoya',
            unique_together={('caso', 'auxiliar')},
        ),
    ]
