# Generated by Django 5.2.6 on 2025-09-14 23:09

import django.core.validators
import gestdocu.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestdocu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(upload_to='documentos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx']), gestdocu.validators.max_size]),
        ),
    ]
