# Generated by Django 5.2.6 on 2025-09-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_caso', models.CharField(max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_finalizacion', models.DateField()),
                ('estado', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('apelaciones', models.TextField()),
                ('tipo_de_caso', models.CharField(max_length=100)),
                ('prioridad', models.CharField(max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
