# Generated by Django 5.2.6 on 2025-09-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='fecha_finalizacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
