# Generated by Django 5.2.6 on 2025-09-15 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0002_alter_caso_fecha_finalizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_expediente', models.CharField(max_length=20)),
                ('fecha_de_creacion', models.DateField()),
                ('Fecha_de_cierre', models.DateField(blank=True, null=True)),
                ('autoridad', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('Proceso', 'Proceso'), ('Cerrado', 'Cerrado')], default='Proceso', max_length=10)),
                ('observaciones', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='caso',
            name='estado',
            field=models.CharField(choices=[('Abierto', 'Abierto'), ('Cerrado', 'Cerrado')], default='Abierto', max_length=10),
        ),
        migrations.AlterField(
            model_name='caso',
            name='prioridad',
            field=models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], default='Baja', max_length=10),
        ),
    ]
